[package]
name = "mirai-matchmaking-server"
version = "0.1.0"
authors = ["Heliozoa <dm89132@gmail.com>"]
edition = "2018"

[dependencies]
mirai-core = { path = "../mirai-core" }
bincode = "1.2.0"
laminar = "0.3.2"
crossbeam-channel = "0.3"
snafu = "0.6"
